### ISSUE TITLE
Can not get shared library spcomlnxarmv7hf.so resource as stream from sp-tty.jar file

### ISSUE THREAD

**Issue by hbjoylee** [RishiGupta12/SerialPundit#11]
Hi,
When I run my java application on Raspberry Pi, it show errors below, can you help me compile a new sp-tty.jar for raspberry pi, thanks.

Exception in thread "main" com.serialpundit.core.SerialComException: /tmp/sp_tuartx1/spcomlnxarmv7hf.so
        at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:322)
        at com.serialpundit.serial.SerialComManager.<init>(SerialComManager.java:367)
       ...................
Caused by: com.serialpundit.core.SerialComException: Can not get shared library spcomlnxarmv7hf.so resource as stream from sp-tty.jar file !
        at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:319)
        ... 3 more

**Comment by RishiGupta12** [comment]
Latest jars are here https://github.com/RishiGupta12/SerialPundit/tree/master/prebuilt-release

**Comment by hbjoylee** [comment]
Thanks Rishi, it solved my problem.

**Comment by Patrick-w** [comment]
Hello @RishiGupta12 , 

I'm getting the exact same error, I'm currently running my java app on Ubuntu.
com.serialpundit.core.SerialComException: No such file or directory
        at com.serialpundit.serial.internal.SerialComPortJNIBridge.openComPort(Native Method)
        at com.serialpundit.serial.SerialComManager.openComPort(SerialComManager.java:618)
        at com.wavemark.pythontest.serial_port.main(serial_port.java:15)
I already updated the jars in vain. 

Any idea why? Thank you!

**Comment by RishiGupta12** [comment]
The serial port device node does not exist: No such file or directory
