### ISSUE TITLE
Application Crash when starting multiple instance of java file.

### ISSUE THREAD

**Issue by umerdhamria1** [RishiGupta12/SerialPundit#44]
Thanks for the great library,
I am facing problem in running two instance on a single machine with different com port, application is generating error 
**com.serialpundit.core.SerialComException: C:\Windows\TEMP\sp_tuartx1\spcomwinx64.dll
	at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:393)
	at com.serialpundit.serial.SerialComManager.<init>(SerialComManager.java:382)
	at ecibautomatebs.ECIBFetchCNIC.Port(ECIBFetchCNIC.java:31)
	at ecibautomatebs.ECIBFetchCNIC.FetchCNIC(ECIBFetchCNIC.java:98)
	at ecibautomatebs.ECIBFetchCNIC.main(ECIBFetchCNIC.java:52)
Caused by: com.serialpundit.core.SerialComException: C:\Windows\TEMP\sp_tuartx1\spcomwinx64.dll
	at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:355)
	... 4 more
Caused by: java.io.FileNotFoundException: C:\Windows\TEMP\sp_tuartx1\spcomwinx64.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:335)**

Please suggest how can i get off of this error. My limitation is to use single machine as send and receiver with continuous running service. 

Thanks

**Comment by RishiGupta12** [comment]
Please use different names for native libraries when creating SerialComManager instance. Documentation (Javadocs) have all the info.
